/*
IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DatabaseLog]') AND type in (N'U'))
DROP TABLE [dbo].[DatabaseLog]
GO
*/

CREATE TABLE [dbo].[DatabaseLog]
(
   [DatabaseLogID] INT      NOT NULL IDENTITY(1,1)
  ,[PostTime]      DATETIME NULL
  ,[DatabaseUser]  SYSNAME  NULL
  ,[Event]         SYSNAME  NULL
  ,[Schema]        SYSNAME  NULL
  ,[Object]        SYSNAME  NULL
  ,[TSQL]          NVARCHAR( MAX ) NULL
  ,[XmlEvent]      XML      NULL
  CONSTRAINT[PK__DatabaseLog] PRIMARY KEY CLUSTERED
  (
    [DatabaseLogID] ASC
  ) WITH ( PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON
 ) ON [PRIMARY]
)
GO

/* Foreign Key Constraints */

/* Default Column Contraints */

/* Column Descriptions */
EXEC sys.sp_addextendedproperty 
  @name=N'MS_Description',
  @value=N'Primary key for DatabaseLog records.',
  @level0type=N'SCHEMA',
  @level0name=N'dbo',
  @level1type=N'TABLE',
  @level1name=N'DatabaseLog',
  @level2type=N'COLUMN',
  @level2name=N'DatabaseLogID'
GO

EXEC sys.sp_addextendedproperty 
  @name=N'MS_Description',
  @value=N'The date and time the DDL change occurred.',
  @level0type=N'SCHEMA',
  @level0name=N'dbo',
  @level1type=N'TABLE',
  @level1name=N'DatabaseLog',
  @level2type=N'COLUMN',
  @level2name=N'PostTime'
GO

EXEC sys.sp_addextendedproperty 
  @name=N'MS_Description',
  @value=N'The user who implemented the DDL change.',
  @level0type=N'SCHEMA',
  @level0name=N'dbo',
  @level1type=N'TABLE',
  @level1name=N'DatabaseLog',
  @level2type=N'COLUMN',
  @level2name=N'DatabaseUser'
GO

EXEC sys.sp_addextendedproperty 
  @name=N'MS_Description',
  @value=N'The type of DDL statement that was executed.',
  @level0type=N'SCHEMA',
  @level0name=N'dbo',
  @level1type=N'TABLE',
  @level1name=N'DatabaseLog',
  @level2type=N'COLUMN',
  @level2name=N'Event'
GO

EXEC sys.sp_addextendedproperty 
  @name=N'MS_Description',
  @value=N'The schema to which the changed object belongs.',
  @level0type=N'SCHEMA',
  @level0name=N'dbo',
  @level1type=N'TABLE',
  @level1name=N'DatabaseLog',
  @level2type=N'COLUMN',
  @level2name=N'Schema'
GO

EXEC sys.sp_addextendedproperty 
  @name=N'MS_Description',
  @value=N'The object that was changed by the DDL statment.',
  @level0type=N'SCHEMA',
  @level0name=N'dbo',
  @level1type=N'TABLE',
  @level1name=N'DatabaseLog',
  @level2type=N'COLUMN',
  @level2name=N'Object'
GO

EXEC sys.sp_addextendedproperty 
  @name=N'MS_Description',
  @value=N'The exact Transact-SQL statement that was executed.',
  @level0type=N'SCHEMA',
  @level0name=N'dbo',
  @level1type=N'TABLE',
  @level1name=N'DatabaseLog',
  @level2type=N'COLUMN',
  @level2name=N'TSQL'
GO

EXEC sys.sp_addextendedproperty 
  @name=N'MS_Description',
  @value=N'The raw XML data generated by database trigger.',
  @level0type=N'SCHEMA',
  @level0name=N'dbo',
  @level1type=N'TABLE',
  @level1name=N'DatabaseLog',
  @level2type=N'COLUMN',
  @level2name=N'XmlEvent'
GO

/* Table Description */
EXEC sys.sp_addextendedproperty 
  @name=N'MS_Description',
  @value=N'Transactional table.',
  @level0type=N'SCHEMA',
  @level0name=N'dbo',
  @level1type=N'TABLE',
  @level1name=N'DatabaseLog'
GO
